# **Statistical Learning for Automation Systems**

       
## *Prof. Simone Formentin*

___

# Pandas

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Import Data as Pandas DataFrame

### CSV Input

In [6]:
df = pd.read_csv('example')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### Excel Input

In [8]:
pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

## Create Pandas DataFrame

In [9]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [10]:
from numpy.random import randn

df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [11]:
df

          W         X         Y         Z
A  0.646737 -1.158519  0.016556 -1.178082
B  1.251252  0.954580 -1.817369 -0.199211
C -1.641257  0.852681 -0.922531 -0.439183
D  0.198733 -0.523257 -1.110781  0.899187
E  0.915964 -1.215992 -0.522069  0.252577

In [15]:
df.tail()

          W         X         Y         Z
A  0.646737 -1.158519  0.016556 -1.178082
B  1.251252  0.954580 -1.817369 -0.199211
C -1.641257  0.852681 -0.922531 -0.439183
D  0.198733 -0.523257 -1.110781  0.899187
E  0.915964 -1.215992 -0.522069  0.252577

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes

In [8]:
df.describe()

              W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.226886 -0.475341  0.115804 -1.090141
std    1.038927  0.634662  0.734061  0.747229
min   -1.239385 -1.426154 -1.070443 -1.831809
25%    0.198174 -0.637742 -0.057069 -1.771386
50%    0.202597 -0.526058  0.378428 -1.206816
75%    0.275178  0.086354  0.508818 -0.421490
max    1.697865  0.126896  0.819283 -0.219204

In [22]:
list(df.columns)

['W', 'X', 'Y', 'Z']

### Selection and Indexing

### Selecting columns

In [25]:
(df['W'])

A    0.646737
B    1.251252
C   -1.641257
D    0.198733
E    0.915964
Name: W, dtype: float64

In [28]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A  0.646737 -1.178082
B  1.251252 -0.199211
C -1.641257 -0.439183
D  0.198733  0.899187
E  0.915964  0.252577

### Add a new column

In [29]:
df['new'] = df['W'] + df['Y']

In [30]:
df

          W         X         Y         Z       new
A  0.646737 -1.158519  0.016556 -1.178082  0.663294
B  1.251252  0.954580 -1.817369 -0.199211 -0.566116
C -1.641257  0.852681 -0.922531 -0.439183 -2.563788
D  0.198733 -0.523257 -1.110781  0.899187 -0.912049
E  0.915964 -1.215992 -0.522069  0.252577  0.393895

### Remove a column

In [34]:
df.drop('new',axis=1,inplace=True)

In [35]:
df

          W         X         Y         Z
A  0.646737 -1.158519  0.016556 -1.178082
B  1.251252  0.954580 -1.817369 -0.199211
C -1.641257  0.852681 -0.922531 -0.439183
D  0.198733 -0.523257 -1.110781  0.899187
E  0.915964 -1.215992 -0.522069  0.252577

In [36]:
df.drop('new',axis=1, inplace = True)

KeyError: "['new'] not found in axis"

In [37]:
df

          W         X         Y         Z
A  0.646737 -1.158519  0.016556 -1.178082
B  1.251252  0.954580 -1.817369 -0.199211
C -1.641257  0.852681 -0.922531 -0.439183
D  0.198733 -0.523257 -1.110781  0.899187
E  0.915964 -1.215992 -0.522069  0.252577

### Remove a row

In [45]:
df.drop('E',axis=0)

          W         X         Y         Z
A  0.646737 -1.158519  0.016556 -1.178082
B  1.251252  0.954580 -1.817369 -0.199211
C -1.641257  0.852681 -0.922531 -0.439183
D  0.198733 -0.523257 -1.110781  0.899187

### Selecting rows

In [49]:
df.loc['A','Z']

-1.1780820380466723

In [50]:
df.iloc[0,-1]

-1.1780820380466723

### Selecting a subset of rows and columns

In [58]:
df.loc['A':'C',['W','Y']]

          W         Y
A  0.646737  0.016556
B  1.251252 -1.817369
C -1.641257 -0.922531

## Conditional Selection

In [66]:
df

          W         X         Y         Z
A  0.646737 -1.158519  0.016556 -1.178082
B  1.251252  0.954580 -1.817369 -0.199211
C -1.641257  0.852681 -0.922531 -0.439183
D  0.198733 -0.523257 -1.110781  0.899187
E  0.915964 -1.215992 -0.522069  0.252577

In [64]:
df[df['W']<0]

          W         X         Y         Z
C -1.641257  0.852681 -0.922531 -0.439183

In [68]:
df['W'] < 0

A    False
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [67]:
df[df['W']<0]['Y']

C   -0.922531
Name: Y, dtype: float64

In [73]:
df[(df['W']<0) & (df['Y'] > -0.5)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []